name: project_x
description: "Software to optimize project, finance, and client management."
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  sqflite_common_ffi: ^2.3.3
  sqlite3_flutter_libs: ^0.5.20
  path: ^1.9.0
  path_provider: ^2.1.2
  rxdart: ^0.27.7
  flutter_secure_storage: ^9.0.0
  window_manager: ^0.3.8
  icons_launcher: ^2.1.7
  intl: ^0.18.1
  flutter_masked_text2: ^0.9.1
  fl_chart: ^0.67.0
  dotted_line: ^3.2.2


dev_dependencies:
  #flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/mulish/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/mulish/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/mulish/Mulish-Medium.ttf
          weight: 500    
        - asset: assets/fonts/mulish/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/mulish/Mulish-Black.ttf
          weight: 900

icons_launcher:
  image_path: "assets/images/app_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    windows:
      enable: true